// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/login": {
            "post": {
                "description": "user login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user login",
                "parameters": [
                    {
                        "description": "login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user login successfully",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "user registration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "user registration",
                "parameters": [
                    {
                        "description": "register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "user register successfully",
                        "schema": {
                            "$ref": "#/definitions/model.RegisterResponse"
                        }
                    }
                }
            }
        },
        "/task": {
            "get": {
                "description": "Retrieve all tasks for a user with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "List all tasks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token value",
                        "name": "auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit of tasks to retrieve",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by task status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to sort by",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Order of sorting (1 for ascending, -1 for descending)",
                        "name": "sortOrder",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task created successfully",
                        "schema": {
                            "$ref": "#/definitions/model.TaskListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError500"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new task for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Create a task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token value",
                        "name": "auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Task creation request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TaskCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Task created successfully",
                        "schema": {
                            "$ref": "#/definitions/model.TaskCreateResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError500"
                        }
                    }
                }
            }
        },
        "/task/{id}": {
            "get": {
                "description": "Get the details of a task by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Retrieve a task by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token value",
                        "name": "auth-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task created successfully",
                        "schema": {
                            "$ref": "#/definitions/model.TaskReadResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError500"
                        }
                    }
                }
            },
            "put": {
                "description": "Update the details of a task by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Update a task by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token value",
                        "name": "auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Task update request",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TaskUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task updated successfully",
                        "schema": {
                            "$ref": "#/definitions/model.TaskUpdateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError500"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a task from the system by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Delete a task by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token value",
                        "name": "auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Task deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/model.TaskDeleteResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError500"
                        }
                    }
                }
            }
        },
        "/tasks/mark-done": {
            "put": {
                "description": "Mark multiple tasks as done for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "Mark multiple tasks as done",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token value",
                        "name": "auth-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Task IDs to mark as done",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.MarkDoneRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tasks marked as done successfully",
                        "schema": {
                            "$ref": "#/definitions/model.MarkTasksAsDoneResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError401"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.ServerError500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.LoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "model.LoginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "token": {
                            "type": "string",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NmY1ODY1NjhiYTAxYjBkOGQ4MzFjMjUiLCJleHAiOjUxNjc2MzY4NzB9.s4U-8Hl6s3hTr0n0Zb9FbYLEGCwO4k5pL5trZxd6AeI"
                        }
                    }
                },
                "message": {
                    "type": "string",
                    "example": "user login successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.MarkDoneRequest": {
            "type": "object",
            "properties": {
                "task_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "60d5ec49c6d8c06e1f20c5a8"
                    ]
                }
            }
        },
        "model.MarkTasksAsDoneResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Task 60d5ec49c6d8c06e1f20c5a8 marked as done."
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "Tasks processed."
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@gmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "test user"
                },
                "password": {
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "model.RegisterResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "user register successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.ServerError401": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "Unauthorized access"
                },
                "status": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "model.ServerError500": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "internal server error"
                },
                "status": {
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "model.Task": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-09-27T14:09:53.259915568+05:30"
                },
                "description": {
                    "type": "string",
                    "example": "task description"
                },
                "id": {
                    "type": "string",
                    "example": "60d5ec49c6d8c06e1f20c5a8"
                },
                "status": {
                    "description": "\"todo\", \"in progress\", \"done\"",
                    "type": "string",
                    "example": "todo / in progress / done"
                },
                "title": {
                    "type": "string",
                    "example": "task title"
                },
                "userID": {
                    "type": "string",
                    "example": "667bd3d9df5113761db9b247"
                }
            }
        },
        "model.TaskCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "task description"
                },
                "status": {
                    "description": "\"todo\", \"in progress\", \"done\"",
                    "type": "string",
                    "example": "todo / in progress / done"
                },
                "title": {
                    "type": "string",
                    "example": "task title"
                }
            }
        },
        "model.TaskCreateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "60d5ec49c6d8c06e1f20c5a8"
                },
                "message": {
                    "type": "string",
                    "example": "Task created successfully."
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.TaskDeleteResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "Task deleted successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.TaskListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Task"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Task list retrieved successfully."
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.TaskReadResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.Task"
                },
                "message": {
                    "type": "string",
                    "example": "Task retrieved successfully."
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.TaskUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Description of the task",
                    "type": "string",
                    "example": "task description"
                },
                "status": {
                    "description": "Status of the task  \"todo\", \"in progress\", \"done\"",
                    "type": "string",
                    "example": "todo / in progress / done"
                },
                "title": {
                    "description": "Title of the task",
                    "type": "string",
                    "example": "task title"
                }
            }
        },
        "model.TaskUpdateResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string",
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "Task updated successfully"
                },
                "status": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "util.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8082",
	BasePath:         "/task-service",
	Schemes:          []string{},
	Title:            "Task management api",
	Description:      "Task management server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
